name: Build cmd/app

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Download dependencies
        run: go mod download

      - name: Create build directories
        run: |
          mkdir -p ./bin/linux_amd64

      - name: Run audit (format, vet)
        run: |
          go fmt ./...
          go vet ./...

      - name: Build for linux/amd64
        env:
          SERVICE_NAME: goalkeepr
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build "-ldflags=-s" -o=./bin/linux_amd64/${{ env.SERVICE_NAME }} ./cmd/app

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: goalkeepr-binary
          path: ./bin/linux_amd64/goalkeepr
